# Specifies the network interface to use for the LocalIP readout
interface = "en0"

# Lengthen uptime output
long_uptime = true

# Lengthen shell output
long_shell = false

# Lengthen kernel output
long_kernel = true

# Toggle between displaying the current shell or your user's default one.
current_shell = true

# Toggle between displaying the number of physical or logical cores of your
# processor.
physical_cores = true

# Themes need to be placed in "$XDG_CONFIG_DIR/macchina/themes" beforehand.
# e.g.:
#  if theme path is /home/foo/.config/macchina/themes/Sodium.toml
#  theme should be uncommented and set to "Sodium"
#
# theme = ""

# Displays only the specified readouts.
# Accepted values (case-sensitive):
#   - host
#   - machine
#   - kernel
#   - distribution
#   - operating-system
#   - desktop-environment
#   - window-manager
#   - resolution
#   - backlight
#   - packages
#   - local-ip
#   - terminal
#   - shell
#   - uptime
#   - processor
#   - processor-load
#   - memory
#   - battery
#   - gpu
#   - disk-space
# Example:
#   show = ["battery", "memory", ...]

show = [
  "Host",
  "Machine",
  "LocalIP",
  "Processor",
  "Memory",
  "Kernel",
  "OperatingSystem",
  "DesktopEnvironment",
  "WindowManager",
  "Terminal",
  "Shell",
]

