# vi:ft=zsh:
# opt out of telemetries
export DOTNET_CLI_TELEMETRY_OPTOUT=1
export HOMEBREW_NO_ANALYTICS=1

# PATHs
# Homebrew
if [ -e "$HOME/.local/homebrew/bin/brew" ]; then
  eval $($HOME/.local/homebrew/bin/brew shellenv)
fi

# Android
if [ -e $HOMEBREW_PREFIX ]; then
  export PATH="$PATH:$HOMEBREW_PREFIX/share/android-commandlinetools/platform-tools"
fi

# other garbages
export PATH=$HOME/.local/bin:$PATH

export GOPATH=$HOME/.local/opt/go
#if [ -e "$HOME/.local/opt/esp/xtensa-esp32-elf/bin" ]; then
#  export PATH="$HOME/.local/opt/esp/xtensa-esp32-elf/bin:$PATH"
#fi

# Preferences
# (just because we can) enable YJIT for when running Ruby 3.2.x or later
export RUBY_YJIT_ENABLE=1

# use nvim
export EDITOR="$(which vi)"
export VISUAL="$(which vi)"

# English please.
export LANG=en_US.UTF-8
