#! vi:ft=zsh
# load plugins
source $HOME/.antigen.conf.zsh

# completion
autoload -Uz compinit
compinit -i

# Prompt
autoload -Uz promptinit
promptinit
zstyle ':completion:*' menu select
setopt COMPLETE_ALIASES

if type starship &>/dev/null; then
  eval "$(starship init zsh)"
else
  prompt walters
fi

autoload -Uz up-line-or-beginning-search down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search

[[ -n "${key[Up]}"   ]] && bindkey -- "${key[Up]}"   up-line-or-beginning-search
[[ -n "${key[Down]}" ]] && bindkey -- "${key[Down]}" down-line-or-beginning-search

# aliases
gcd() {
  if (type ghq&>/dev/null) && (type peco&>/dev/null); then
    if [ $# -eq 0 ]; then
      cd $(ghq root)/$(ghq list | peco)
    else
      cd $(ghq root)/$(ghq list | peco --query $@)  
    fi
  fi
}


if where rbenv &>/dev/null; then
  # Load rbenv automatically by appending
  # the following to ~/.zshrc:

  eval "$(rbenv init - zsh)"
  export PATH="$(brew --prefix)/bin:$PATH"
fi

if where pyenv &>/dev/null; then
  # Initialize pyenv
  export PYENV_ROOT="$HOME/.pyenv"
  export PATH="$PYENV_ROOT/shims:$PATH"
  eval "$(pyenv init -)"
fi

if where goenv &>/dev/null; then
  # Load goenv automatically by appending
  # the following to ~/.zshrc:

  eval "$(goenv init -)"
  export PATH=$GOROOT/bin:$PATH
  export PATH=$PATH:$GOPATH/bin
fi

if where nodenv &>/dev/null; then
  # Load nodenv automatically by appending
  # the following to ~/.zshrc:

  eval "$(nodenv init -)"
fi

if where direnv &>/dev/null; then
  # Load direnv
  eval "$(direnv hook zsh)"
fi

# Greetings!
if where neofetch &>/dev/null; then
  neofetch
fi

# If not running interactively, do not do anything
[[ $- != *i* ]] && return
# TMUX
if where tmux &>/dev/null; then
  # if no session is started, start a new session
  if [ -z ${TMUX} ]; then
    tmux -As main
  fi

  # when quitting tmux, try to attach
  while test -z ${TMUX}; do
    tmux attach || break
  done
fi
